SELECT * FROM ROLES;
SELECT * FROM AUTHORITIES;
SELECT * FROM MEMBERS;

DESC MEMBERS;

DELETE FROM members WHERE email = 'univcss@naver.com';
COMMIT;

-- 계정 권한 테스트
UPDATE members SET isApproved = 0;
COMMIT;

DELETE FROM authorities
COMMIT;


SELECT * FROM BOARDFORM;
SELECT * FROM BOARDKIND;

--
SELECT * FROM BOARDGROUP;
SELECT * FROM BOARD;
SELECT * FROM HISTORY;
SELECT * FROM MEDIA;

DELETE FROM HISTORY;
DELETE FROM MEDIA;
DELETE FROM BOARD;
DELETE FROM BOARDGROUP;
COMMIT;


